# Generated by Django 4.2 on 2025-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(),
        ),
    ]
